"""empty message

Revision ID: 27e3b4ebb7d0
Revises: 1a168d68efe9
Create Date: 2023-07-06 23:09:33.189063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27e3b4ebb7d0'
down_revision = '1a168d68efe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_date', sa.DateTime(), nullable=True))
    op.drop_column('order', 'order_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('order', 'order_date')
    # ### end Alembic commands ###
